# Generated by Django 5.2 on 2025-04-05 02:33

import cloudinary_storage.storage
import cloudinary_storage.validators
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('technologies', django_jsonform.models.fields.JSONField(default=list)),
                ('video', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[cloudinary_storage.validators.validate_video])),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/projects/')),
                ('github', models.CharField(blank=True, max_length=500, null=True)),
                ('demo', models.CharField(blank=True, max_length=300, null=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
