# Generated by Django 5.2 on 2025-04-05 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
