# Generated by Django 5.1.7 on 2025-04-01 13:15

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=django_jsonform.models.fields.JSONField(default=list),
        ),
    ]
