# Generated by Django 5.2 on 2025-04-05 02:03

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='love',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/love/'),
        ),
        migrations.AlterField(
            model_name='love',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/love/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
