# Generated by Django 5.1.7 on 2025-04-01 13:08

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=django_jsonform.models.fields.JSONField(default=list),
        ),
    ]
