name: Keep Render Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # every 10 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl personal-blog
        run: curl -s https://personal-blog-l9i7.onrender.com/ping
